### ISSUE TITLE
Add proxy to snscrape twitter search

### ISSUE THREAD

**Issue by royantoine** [ambanum/information-manipulation-analyzer-processor#48]
The data collection process is facing problems and the current server seems to have been banned from Twitter. Adding a proxy in snscrape command should solve this problem.

see [this link](https://github.com/JustAnotherArchivist/snscrape/issues/74) for a related issue on the `snscrape` github page 

The easiest  way to use a proxy when running the command is to set the `HTTP_PROXY` environment variable. The library `request` that is used by `snscrape` will then use it to make its request to the Twitter website. 
So the `snscrape` command would just needs to be modified as follow in the `src/common/node-snscrape.ts` file:
line 148 `cmd = 'export HTTP_PROXY=${PROXY}; ${SNSCRAPE_PATH} --with-entity --max-results ${ ...'`
line 277 `cmd = 'export HTTP_PROXY=${PROXY}; ${SNSCRAPE_PATH} --with-entity --max-results 0 --jsonl twitter-user ${username}'`
with `PROXY` taken from a list of proxys

The `scnscrape` code could be also modified directly and especially the file `snscrape/snscrape/_cli.py` adding `export HTTP_PROXY=${PROXY}` to the beginning of the `main` function. However, this change would be removed each time the `snscrape` library is updated in the code.

**Comment by martinratinaud** [comment]
Thanks @royantoine I will try to implement with this env variable then
